### ISSUE TITLE
Gradio APP Fork Application

### ISSUE THREAD

**Issue by ZhaoQiiii** [arielnlee/Platypus#13]
Hello , I am an employee of Shanghai Artificial Intelligence Laboratory (CVPR2023 Best Paper Obtained Laboratory), we currently operate a platform （https://openxlab.org.cn/apps） similar to HuggingFace in China, and hope to get your authorization to build Platypus Gradio application (We will provide free GPU resources, such as A10/A100), as well as hosting Platypus Checkpoint, so that Platypus can better spread and promote this work in China, so that more people can experience the capabilities brought by AI. Thanks!

**Comment by lilloukas** [comment]
Hello,

As long as the use of the model follows the [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license, absolutely!
