### ISSUE TITLE
Timeout when training in distributed mode

### ISSUE THREAD

**Issue by Godofnothing** [arielnlee/Platypus#19]
When training Llama2-7b using the provided script, I encounter eventually timeout in NCCL communication. 

**Error**
```bash
[E ProcessGroupNCCL.cpp:828] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=53, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1805911 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:455] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:460] To avoid data inconsistency, we are taking the entire process down.
```
**The script launched**
```python
torchrun --nproc_per_node=2 --master_port=1234 finetune.py \
    --base_model meta-llama/Llama-2-7b-hf \
    --data-path garage-bAInd/Open-Platypus \
    --output_dir ./llama2-platypus-7b \
    --batch_size 16 \
    --micro_batch_size 4 \
    --num_epochs 1 \
    --learning_rate 0.0004 \
    --cutoff_len 4096 \
    --val_set_size 0 \
    --lora_r 16 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --lora_target_modules '[gate_proj, down_proj, up_proj]' \
    --train_on_inputs False \
    --add_eos_token False \
    --group_by_length False \
    --prompt_template_name alpaca \
    --lr_scheduler 'cosine' \
    --warmup_steps 100
  ```
  **Environment & System**

- 2 RTX A6000 GPU with 48 VRAM
- 1 Tb RAM

```
pytorch                   2.0.1           py3.10_cuda11.7_cudnn8.5.0_0    pytorch
pytorch-cuda              11.7                 h778d358_5    pytorch

transformers             4.31.0
datasets                 2.13.1
accelerate               0.20.3
```

Some suggestions related to this error were proposed in the [thread](https://github.com/huggingface/accelerate/issues/314), but none did work for me.

**Comment by senwen616** [comment]
same error  A100 80

**Comment by amulil** [comment]
same error A100 40

**Comment by arielnlee** [comment]
Hi All! Have you tried the steps below:
If you're fine-tuning LLaMa-2 7B, please add bf16=True and change fp16=False in the HF trainer. LLaMa-1 7B works as is. This only applies to LLaMa-2 7B. Additionally, if you are using 1 GPU, please change ddp_find_unused_paramters=False in the HF trainer.

**Comment by amulil** [comment]
> Hi All! Have you tried the steps below: If you're fine-tuning LLaMa-2 7B, please add bf16=True and change fp16=False in the HF trainer. LLaMa-1 7B works as is. This only applies to LLaMa-2 7B. Additionally, if you are using 1 GPU, please change ddp_find_unused_paramters=False in the HF trainer.

I have 8A100-40g. I try to fine-tune Llama2-13B on 8 gpus by using the shell below.But I met the problem above.
```shell
torchrun --nproc_per_node=8 --master_port=1234 finetune.py \
    --base_model /data/home/wangyongxin/model/llama2/13b/origin/hf \
    --data-path garage-bAInd/Open-Platypus \
    --output_dir /data/home/wangyongxin/model/llama2/13b/sft/platypus2-13b-offical \
    --batch_size 16 \
    --micro_batch_size 1 \
    --num_epochs 1 \
    --learning_rate 0.0004 \
    --cutoff_len 4096 \
    --val_set_size 0 \
    --lora_r 16 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --lora_target_modules '[gate_proj, down_proj, up_proj]' \
    --train_on_inputs False \
    --add_eos_token False \
    --group_by_length False \
    --prompt_template_name alpaca \
    --lr_scheduler 'cosine' \
    --warmup_steps 100
```

**Comment by Godofnothing** [comment]
@arielnlee 
Yes, I have set bf16=True and fp=16 False when running the code above. 
Note that the problem takes part in distributed setup. Single GPU run works well.

**Comment by arielnlee** [comment]
And you’re using torchrun with a single GPU?

**Comment by Godofnothing** [comment]
@arielnlee  I am not using `torchrun` with a single GPU.
 As mentioned in the issue, I get the error when using 2 A6000 with `torchrun`.  
 For  a single GPU run I simply do `python finetune.py <args>`

**Comment by arielnlee** [comment]
Apologies, I understand. What version of bitsandbytes are you using? Also, are you using wandb and/or runpods?

**Comment by Godofnothing** [comment]
@arielnlee 
I have the following version of bnb:
`bitsandbytes             0.39.0`
Problem takes place either with wandb enabled or disabled.

**Comment by arielnlee** [comment]
Got it. I am going to attempt to replicate this on runpods now. Will get back to you!

**Comment by arielnlee** [comment]
I haven't been able to replicate this. Will you try using bitsandbytes==0.37.2? 

Does the hang occur after mapping?

**Comment by Godofnothing** [comment]
@arielnlee I tried again with the latest version - same issue. Hang occurs during training at random moment of time, usually after 100-200 steps.

**Comment by arielnlee** [comment]
Did you also try with bitsandbytes==0.37.2?

**Comment by Godofnothing** [comment]
@arielnlee downgrading bitandbytes leads to errors even before training, but I've tried to run this code on other machine with A100 GPUs and the training completed succesfully. 
Seems like it is a sort of environment issue rather than the problem with the code itself.

**Comment by amulil** [comment]
> @arielnlee downgrading bitandbytes leads to errors even before training, but I've tried to run this code on other machine with A100 GPUs and the training completed succesfully. Seems like it is a sort of environment issue rather than the problem with the code itself.

Could you show your environment to help others to avoid this problem？thanks!! @Godofnothing

**Comment by Godofnothing** [comment]
@amulil 
the configuration that runs successfully is the following:
```bash
pytorch-cuda              11.8                 h7e8668a_5    pytorch

torch                    2.0.1
datasets                 2.13.1
transformers             4.31.0
accelerate               0.21.0
bitsandbytes             0.41.1
```
Host is equipped with Nvidia A100 GPU and the following version of Nvidia driver: `Driver Version: 510.39.01`.

**Comment by arielnlee** [comment]
@Godofnothing @amulil  
It also works with cuda 11.7 and all of the versions listed in the requirements.txt file (the only version difference above is bitsandbytes) - just ran it. Thanks!
