### ISSUE TITLE
About prompt template

### ISSUE THREAD

**Issue by IcyGrain** [arielnlee/Platypus#7]
I noticed that you used alpaca prompt template for fine tuning, but Meta said they are using their own prompt template for instruct tuning, will it matter the final result???

https://huggingface.co/meta-llama/Llama-2-7b-chat-hf

To get the expected features and performance for the chat versions, a specific formatting needs to be followed, including the INST and <<SYS>> tags, BOS and EOS tokens, and the whitespaces and breaklines in between (we recommend calling strip() on inputs to avoid double-spaces). See our reference code in github for details: [chat_completion](https://github.com/facebookresearch/llama/blob/main/llama/generation.py#L212).

**Comment by arielnlee** [comment]
Meta is using their own prompt template for instructing-tuning, but since we are fine-tuning on their base model, not their chat model, it's not an issue.
